tap "homebrew/versions"

brew "ack"
brew "ag"
brew "awscli"
brew "consul"
brew "ctags"
brew "fzf"
brew "elixir"
brew "git"
brew "git-lfs"
brew "go"
brew "hg"
brew "htop"
brew "hub"
brew "imagemagick"
brew "jq"
brew "kubectl"
brew "launchdns"
brew "macvim", args: ["--with-override-system-vim"]
brew "mas"
brew "mtr"
# brew "phantomjs198"
brew "ponysay"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby-build"
brew "terraform"
brew "tmux"
brew "unrar"
brew "watch"
brew "wget"
brew "yarn"

cask "atom"
# cask "cord"
cask "dropbox"
# cask "firefox"
# cask "google-chrome"
cask "gpgtools"
cask "google-cloud-sdk"
cask "hammerspoon"
# cask "harvest"
cask "heroku-toolbelt"
# cask "intellij-idea-ce"
cask "iterm2"
cask "karabiner-elements"
cask "lastpass"
cask "phantomjs"
cask "postgres"
# cask "screenhero"
# cask "skitch"
# cask "skype"
# cask "slack"
cask "vagrant"
cask "vlc"
