tap "homebrew/versions"

brew "ack"
brew "awscli"
brew "ctags"
brew "hg"
brew "hub"
brew "imagemagick"
brew "jq"
brew "macvim", args: ["--override-system-vim"]
# brew "phantomjs198"
brew "rbenv"
brew "ruby-build"
brew "terraform"
brew "tmux"
brew "unrar"
brew "wget"

cask "atom"
# cask "cord"
cask "dockertoolbox"
cask "dropbox"
# cask "firefox"
# cask "google-chrome"
# cask "harvest"
# cask "heroku-toolbelt"
# cask "intellij-idea-ce"
cask "iterm2"
cask "lastpass"
# cask "postgres"
# cask "screenhero"
# cask "skitch"
# cask "skype"
# cask "slack"

